import "./theme.css";
import "@coinbase/onchainkit/styles.css";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { FarcasterSDKInitializer } from "../app/components/FarcasterSDK";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
}; 

export async function generateMetadata(): Promise<Metadata> {
  const URL = process.env.NEXT_PUBLIC_URL;
  
  // Frame configuration for embeds
  const frameConfig = {
    version: "1", // Changed from "next" to "1" for better compatibility
    imageUrl: process.env.NEXT_PUBLIC_APP_HERO_IMAGE,
    button: {
      title: `Launch ${process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME}`,
      action: {
        type: "launch_frame",
        name: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
        url: URL,
        splashImageUrl: process.env.NEXT_PUBLIC_SPLASH_IMAGE,
        splashBackgroundColor: process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR,
      },
    },
  };

  return {
    title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
    description: process.env.NEXT_PUBLIC_APP_DESCRIPTION || "Generated by `create-onchain --mini`, a Next.js template for MiniKit",
    openGraph: {
      title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
      description: process.env.NEXT_PUBLIC_APP_DESCRIPTION,
      images: process.env.NEXT_PUBLIC_APP_HERO_IMAGE ? [process.env.NEXT_PUBLIC_APP_HERO_IMAGE] : [],
    },
    other: {
      // Primary meta tag for Farcaster
      "fc:miniapp": JSON.stringify(frameConfig),
      // Backward compatibility
      "fc:frame": JSON.stringify(frameConfig),
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        <Providers>
          {children}
          <FarcasterSDKInitializer />
        </Providers>
      </body>
    </html>
  );
}