export const fortunes = [
  "To HODL or not to HODL, that is the question 🎭",
  "All that glisters is not gold... but Bitcoin might be ✨",
  "A fool and his crypto are soon parted 🃏",
  "Thou dost buy high and sell low, as is tradition 📉",
  "What's done cannot be undone... unless thou hast thy seed phrase 🔐",
  "The course of true love never did run smooth, nor crypto prices 💔",
  "Some are born great, some achieve greatness, some buy shitcoins 🚀",
  "Neither a borrower nor a lender be, but DeFi lending is tempting 🏦",
  "This above all: to thine own keys be true 🗝️",
  "All the world's a stage, and all crypto traders merely players 🎪",
  "Better three hours too soon than a minute too late to buy the dip 📈",
  "Brevity is the soul of wit, and thy portfolio 📊",
  "There is method in madness, but not in thy trading strategy 🤪",
  "Double, double toil and trouble; crypto burn and portfolio bubble! 🔥",
  "Now is the winter of our discontent... made glorious summer by ETH 🌞",
  "A rose by any other name would smell as sweet, but rugpulls still stink 🌹",
  "Cowards die many times before their deaths; diamond hands die but once 💎",
  "If music be the food of love, play on; if hopium be the food of hodlers... 🎵",
  "Give every man thy ear, but few thy voice, and none thy private keys 👂",
  "The fault, dear Brutus, is not in our stars, but in our stop losses ⭐",
  "To be, or not to be liquidated, that is the question ⚰️",
  "Wherefore art thou, moon? Deny thy bear market and refuse thy name! 🌙",
  "A horse! A horse! My kingdom for a horse... or one Bitcoin 🐎",
  "Et tu, Brute? Even you sold at the bottom? 🗡️",
  "Cry 'Havoc!' and let slip the dogs of FOMO 🐕",
  "Friends, Romans, countrymen, lend me your ears... and your leverage 👥",
  "Beware the Ides of March... and all other trading days 📅",
  "Thy wallet shall vanish swifter than a jester's dignity. 🎭",
  "Beware: thy gains are but illusions wrapped in green candles. 🕯️",
  "A fool's pump is followed by a knave's dump. 🎢",
  "Thy gas fee shall bite harder than love's first betrayal. 💸",
  "Thy Lambo dreams shall dissolve into the tavern floor. 🍻",
  "An airdrop promised is often but hot wind. 💨",
  "Ye shall awaken to red candles and much weeping. 😭",
  "Apeth boldly, but prepareth to sleepeth in poverty. 🦍",
  "Thou who followeth memecoins shall dance with beggars. 🤡",
  "A chart too green must surely redden by sunset. 🟩🟥",
  "The bull may prance, but the bear lies ever near. 🐂🐻",
  "Shill softly, for thy token is naught but vapor. 💨",
  "Great gains come to those who dump upon the greater fool. 😈",
  "Thine roadmap is but a minstrel's tale. 📜",
  "Thou wilt eat noodles tonight… and tomorrow… and forever. 🍜",
  "Presale riches end in peasant tears. 🧻",
  "Thou shalt mint, and rue the day. 🤔",
  "Hark! Thy coin desireth thee broke. 💀",
  "Ye shall dream of riches and awaken to dust. 🌪️",
  "A red candle is but tomorrow's heartbreak delivered early. 🩸",
  "Beware the green wick… it is but bait. 🕯️",
  "Thou shalt stake… and watch thy gold wither. 🐌",
  "Peasant by morning, peasant by evening — crypto changeth not thy fate. 🏚️",
  "Thy seed phrase shalt flee like a scorned mistress. 🫣",
  "Thy bags are cursed heirlooms, passed to thine children. 🎒",
  "Thou wilt gamble for gold and win naught but onions. 🧅",
  "Strong hands are no match for thy weak mind. 🤯",
  "The chart shall climbeth… only to belly-flop. 🏊‍♂️",
  "Thine treasure is but digital vapour with a fancy name. 💨",
  "Hold fast! Or better yet, run fast. 🏃‍♂️",
  "Thou who trade without thought shall feast upon air. 🌬️",
  "Thy staking APY shall vanish quicker than thy lover. 🥀",
  "Rug or riches? The coin shall decide… cruelly. 🪙",
  "Liquidity flee'th faster than wenches at sunrise. 🌅",
  "Thy pumps shall turn to dumps before thine ale groweth warm. 🍺",
  "Thy portfolio shall resemble a battlefield… and thou art losing. ⚔️",
  "Thy gain is but bait for thy neighbor's loss. 🎣",
  "Thou art but one whale fart away from ruin. 🐋💨",
  "Sleep not, lest thy bags be lighter by dawn. 🪦",
  "Thine coin is mooning… towards the center of the earth. 🌙🌍",
  "Thy DEX is but a den of jesters. 🤡",
  "Rugpulls lurketh where greed doth flourish. 🏴‍☠️",
  "Thou shalt flip… and landeth upon thy face. 🪃",
  "Thy bull run is but a donkey's trot. 🐂🐴",
  "Cry havoc, and prepare thy wallet for slaughter. 🗡️",
  "Green candles doth bring false hope to feeble minds. 🟢",
  "Thou shalt whisper 'retire rich'… and scream 'rekt' instead. 😵‍💫"
];

export function getRandomFortune(): string {
  return fortunes[Math.floor(Math.random() * fortunes.length)];
}

export function getFortuneOfTheDay(): string {
  // Use date as seed for consistent daily fortune
  const today = new Date().toDateString();
  const seed = today.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  return fortunes[seed % fortunes.length];
}